[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.zip"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev"]

[phases.build]
cmds = ["php artisan config:cache", "php artisan route:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
